name: build

on:
  push:
    branches: [ main ]
    paths:
      - '**.cs'
      - '**.csproj'
  pull_request:
    branches: [ main ]
    paths:
      - '**.cs'
      - '**.csproj'

env:
  DOTNET_VERSION: '6.0'

jobs:
  build:

    name: build-linux
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install .NET Core
      uses: actions/setup-dotnet@v2.1.0
      with:
        dotnet-version: $DOTNET_VERSION

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build -c Release --no-restore